import { DataSource, type DataSourceOptions } from 'typeorm';
import { ENTITIES } from '../common/entities.js';
import { MIGRATIONS } from './migrations.js';

/**
 * The single TypeORM definition, shared by the running application and the
 * `typeorm` CLI. Previously the app configured its connection inline and the CLI
 * had nothing to talk to, so a migration could only ever be run by hand-editing
 * `app.module.ts`.
 *
 * The npm scripts that invoke the CLI run node with `--env-file-if-exists=.env`,
 * because the CLI starts outside `ConfigModule` and would otherwise see an
 * empty environment. No dotenv import is needed, and none is taken from
 * `@nestjs/config`'s transitive dependencies.
 */
export function databaseOptions(
  env: NodeJS.ProcessEnv = process.env,
): DataSourceOptions {
  return {
    type: 'postgres',
    host: env.DB_HOST ?? 'localhost',
    port: Number(env.DB_PORT ?? 5432),
    username: env.DB_USERNAME ?? 'postgres',
    password: env.DB_PASSWORD || 'postgres',
    database: env.DB_DATABASE ?? 'ops',
    entities: ENTITIES,
    migrations: MIGRATIONS,
    // Naming strategy and column options are pinned so a migration written by
    // hand and one generated by `migration:generate` produce the same SQL.
    migrationsTableName: 'migrations',
  };
}

/** Only the CLI needs this export; the application resolves its own DataSource. */
export default new DataSource(databaseOptions());
